"""
Cross-dialect helpers for JSON columns and timestamp expressions.

pf-core supports three SQL dialects: MySQL 8+, PostgreSQL 14+, SQLite 3.38+.
Most schema work goes through SQLAlchemy (which handles dialect translation
itself), but raw SQL fragments — used in Alembic migrations and the rare
runtime query that must hit a JSON path — need explicit dialect mapping.

Use these helpers anywhere you'd otherwise write `if dialect == "mysql": ...`.

Usage::

    from pf_core.db.json_compat import (
        json_col_type, json_extract_sql, now_expr,
        autoinc_pk, small_autoinc_pk, tiny_autoinc_pk,
        timestamp_type, mediumtext_type, decimal_type, bool_type,
    )

    ddl = f"name {json_col_type(dialect)} NOT NULL"
    expr = json_extract_sql(dialect, "details", "ratio")
    ts = now_expr(dialect)
"""

from __future__ import annotations

SUPPORTED_DIALECTS = ("mysql", "postgresql", "sqlite")


def _check(dialect: str) -> str:
    if dialect not in SUPPORTED_DIALECTS:
        raise ValueError(f"unsupported dialect {dialect!r}; expected one of {SUPPORTED_DIALECTS}")
    return dialect


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------


def json_col_type(dialect: str) -> str:
    """Return the column type string for a JSON-bearing column."""
    return {"mysql": "JSON", "postgresql": "JSONB", "sqlite": "TEXT"}[_check(dialect)]


def json_extract_sql(dialect: str, col: str, path: str) -> str:
    """Return a SQL fragment that extracts ``path`` from ``col``.

    ``path`` is a dotted JSON path without a leading ``$.`` — e.g. ``"ratio"``
    or ``"details.flagged"``. Use sparingly; pf-core schema avoids JSON-path
    queries on hot paths.
    """
    _check(dialect)
    if dialect == "mysql":
        return f"JSON_EXTRACT({col}, '$.{path}')"
    if dialect == "postgresql":
        # ->> returns text; use -> for jsonb-typed access
        return f"{col}->>'{path}'"
    return f"json_extract({col}, '$.{path}')"


# ---------------------------------------------------------------------------
# Timestamps
# ---------------------------------------------------------------------------


def now_expr(dialect: str, *, fractional: bool = True) -> str:
    """Return the SQL expression for "current UTC timestamp".

    SQLite compares as text, so the shape must match how SQLAlchemy renders a
    bound ``DateTime``: ``strftime('%f')`` gives three fractional digits against
    its six, which sorts a stamped row below its own round-trip. Hence ``%f000``.

    MySQL gets ``CURRENT_TIMESTAMP(6)``; the bare form truncates to seconds. In
    DDL ``fractional`` must match ``timestamp_type``'s, or MySQL rejects the
    statement (ERROR 1067).
    """
    _check(dialect)
    if dialect == "sqlite":
        return "strftime('%Y-%m-%d %H:%M:%f000', 'now')"
    if dialect == "mysql":
        return "CURRENT_TIMESTAMP(6)" if fractional else "CURRENT_TIMESTAMP"
    return "CURRENT_TIMESTAMP"


def timestamp_type(dialect: str, *, fractional: bool = True) -> str:
    """Return the column type string for a timestamp column.

    Args:
        fractional: Include microsecond precision (MySQL ``TIMESTAMP(6)``).
            Must match the ``fractional`` passed to :func:`now_expr` and
            :func:`on_update_now_clause` for the same column.
    """
    _check(dialect)
    if dialect == "mysql":
        return "TIMESTAMP(6)" if fractional else "TIMESTAMP"
    if dialect == "postgresql":
        return "TIMESTAMPTZ"
    return "TEXT"  # SQLite stores ISO 8601 strings


# ---------------------------------------------------------------------------
# Numeric / scalar types
# ---------------------------------------------------------------------------


def autoinc_pk(dialect: str) -> str:
    """Return the column type string for a regular auto-increment INT primary key."""
    _check(dialect)
    if dialect == "mysql":
        return "INT NOT NULL AUTO_INCREMENT PRIMARY KEY"
    if dialect == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY"  # SQLite: INTEGER PRIMARY KEY is rowid alias


def small_autoinc_pk(dialect: str) -> str:
    """Auto-increment SMALLINT primary key (~65k rows)."""
    _check(dialect)
    if dialect == "mysql":
        return "SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY"
    if dialect == "postgresql":
        return "SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY"


def tiny_autoinc_pk(dialect: str) -> str:
    """Auto-increment TINYINT primary key (~255 rows)."""
    _check(dialect)
    if dialect == "mysql":
        return "TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY"
    if dialect == "postgresql":
        return "SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY"


def fk_int_type(dialect: str, *, size: str = "int") -> str:
    """Return the column type string for a foreign-key INT column.

    ``size``: ``"int"``, ``"small"``, or ``"tiny"`` — match the referenced PK.
    """
    _check(dialect)
    if dialect == "mysql":
        return {
            "int": "INT",
            "small": "SMALLINT UNSIGNED",
            "tiny": "TINYINT UNSIGNED",
        }[size]
    if dialect == "postgresql":
        return {"int": "INTEGER", "small": "SMALLINT", "tiny": "SMALLINT"}[size]
    return "INTEGER"


def mediumtext_type(dialect: str) -> str:
    """Return the column type string for a large text column (rendered prompts, raw responses)."""
    _check(dialect)
    if dialect == "mysql":
        return "MEDIUMTEXT"
    return "TEXT"  # Postgres and SQLite both have unlimited TEXT


def decimal_type(dialect: str, precision: int = 10, scale: int = 6) -> str:
    """Return the column type string for a fixed-precision decimal (e.g. cost_usd)."""
    _check(dialect)
    if dialect == "mysql":
        return f"DECIMAL({precision},{scale})"
    if dialect == "postgresql":
        return f"NUMERIC({precision},{scale})"
    return "REAL"  # SQLite has no DECIMAL — use REAL


def bool_type(dialect: str) -> str:
    """Return the column type string for a boolean column."""
    _check(dialect)
    if dialect == "mysql":
        return "TINYINT(1)"
    if dialect == "postgresql":
        return "BOOLEAN"
    return "INTEGER"  # SQLite: 0/1


# ---------------------------------------------------------------------------
# DDL clauses
# ---------------------------------------------------------------------------


def on_update_now_clause(dialect: str, *, fractional: bool = True) -> str:
    """Return the inline DDL clause that sets a column to NOW() on update.

    MySQL has native ``ON UPDATE CURRENT_TIMESTAMP``. Postgres and SQLite
    require a separate trigger — this returns an empty string and the caller
    must emit the trigger SQL elsewhere.

    ``fractional`` must match the column's fsp and the DEFAULT's; see
    :func:`now_expr`.
    """
    _check(dialect)
    if dialect == "mysql":
        return "ON UPDATE CURRENT_TIMESTAMP(6)" if fractional else "ON UPDATE CURRENT_TIMESTAMP"
    return ""


def insert_ignore_prefix(dialect: str) -> str:
    """Return the SQL prefix for an INSERT-or-skip-on-duplicate operation.

    MySQL: ``INSERT IGNORE``
    SQLite/Postgres: ``INSERT OR IGNORE`` is SQLite-only; Postgres uses
    ``ON CONFLICT DO NOTHING`` as a *suffix*. For Postgres callers must use
    the suffix form instead — this helper returns ``"INSERT"`` and the caller
    appends ``ON CONFLICT DO NOTHING``.
    """
    _check(dialect)
    if dialect == "mysql":
        return "INSERT IGNORE"
    if dialect == "sqlite":
        return "INSERT OR IGNORE"
    return "INSERT"  # Postgres caller adds ON CONFLICT DO NOTHING
