"""Dialect-agnostic upserts as SQLAlchemy constructs — no vendor-specific SQL, no driver imports.

Complements :mod:`pf_core.db.json_compat` (which returns portable type / SQL *strings* for raw DDL):
when a consumer uses ``Table`` metadata, these build the live dialect's insert-on-conflict construct
so the code never reaches for SQLite-only ``INSERT OR IGNORE`` / ``INSERT OR REPLACE`` (nor a
hand-rolled ``is_mysql`` branch). SQLite, PostgreSQL, and MySQL/MariaDB all behave identically.

How each dialect is built — the goal is the *same* observable behaviour everywhere:

* **SQLite / PostgreSQL** use ``ON CONFLICT (conflict) DO NOTHING`` / ``DO UPDATE`` plus
  ``RETURNING`` — the latter gives ``insert_ignore`` a reliable inserted-count, because
  ``ON CONFLICT DO NOTHING`` reports ``rowcount = -1`` (unknown) on psycopg.
* **MySQL / MariaDB** have no ``RETURNING`` for these statements. ``upsert`` uses
  ``ON DUPLICATE KEY UPDATE col = VALUES(col)``. ``insert_ignore`` uses a *no-op*
  ``ON DUPLICATE KEY UPDATE pk = pk`` — **not** ``INSERT IGNORE``: the latter would also downgrade
  truncation / NOT-NULL / FK errors to warnings (silent data corruption), whereas the no-op skips
  only on a duplicate key, exactly like ``ON CONFLICT DO NOTHING``. The count comes from ``rowcount``
  (1 = inserted, 0 = skipped under SQLAlchemy's default, which does not set ``CLIENT_FOUND_ROWS``).

Dialect-specific SQL is generated by SQLAlchemy's own compilers — importing
``sqlalchemy.dialects.mysql`` etc. needs no database driver, so this module stays dependency-light.

Usage::

    from pf_core.db import insert_ignore, upsert

    insert_ignore(conn, users, {"slug": "acme", "name": "Acme"}, conflict=["slug"])
    upsert(conn, sources, {"source": "import", "note": n},
           conflict=["source"], update=["note"])
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from sqlalchemy import Table
from sqlalchemy.engine import Connection

from pf_core.exceptions import InvalidInputError

# MySQL and MariaDB report different dialect names but share the same insert construct
# (``ON DUPLICATE KEY UPDATE``, no ``RETURNING``).
_MYSQL_DIALECTS = ("mysql", "mariadb")


def _dialect_insert(name: str):
    """Return the dialect-specific ``insert()`` constructor for dialect ``name``.

    Imports the dialect lazily — the construct compiles without a DBAPI driver installed.
    """
    if name == "postgresql":
        from sqlalchemy.dialects.postgresql import insert
        return insert
    if name == "sqlite":
        from sqlalchemy.dialects.sqlite import insert
        return insert
    if name in _MYSQL_DIALECTS:
        from sqlalchemy.dialects.mysql import insert
        return insert
    raise NotImplementedError(
        f"pf_core.db upsert: dialect {name!r} not supported — "
        "use SQLite, PostgreSQL, or MySQL/MariaDB."
    )


def _first_key_column(table: Table):
    """The column to key a RETURNING / no-op-update off — the first PK column (any column if none)."""
    cols = list(table.primary_key.columns) or list(table.columns)
    return cols[0]


def _insert_ignore_stmt(name: str, table: Table, values: dict[str, Any], conflict: Sequence[str]):
    """Build the INSERT-or-skip statement for dialect ``name``.

    Postgres/SQLite emit ``ON CONFLICT (conflict) DO NOTHING`` with ``RETURNING`` so the caller can
    detect insertion. MySQL/MariaDB emit a no-op ``ON DUPLICATE KEY UPDATE pk = pk`` — the conflict
    target is implicit there (any duplicate key), and the caller reads ``rowcount``.
    """
    insert = _dialect_insert(name)
    if name in _MYSQL_DIALECTS:
        ins = insert(table).values(**values)
        pk = _first_key_column(table)
        # ``pk = pk`` references the *existing* row value → a true no-op that changes nothing and
        # only fires on a duplicate key. Never key off ``ins.inserted`` here: on a conflict over a
        # different unique key that would rewrite the PK.
        return ins.on_duplicate_key_update({pk.name: pk})
    return (
        insert(table)
        .values(**values)
        .on_conflict_do_nothing(index_elements=list(conflict))
        .returning(_first_key_column(table))
    )


def _upsert_stmt(
    name: str,
    table: Table,
    values: dict[str, Any],
    conflict: Sequence[str],
    update: Sequence[str],
):
    """Build the INSERT-or-update statement for dialect ``name``.

    Postgres/SQLite use ``ON CONFLICT (conflict) DO UPDATE``; MySQL/MariaDB use
    ``ON DUPLICATE KEY UPDATE`` (conflicting key implicit). Both overwrite the ``update`` columns
    from the incoming row.
    """
    insert = _dialect_insert(name)
    ins = insert(table).values(**values)
    if name in _MYSQL_DIALECTS:
        # ``col = VALUES(col)`` — the portable form that works on both MySQL and MariaDB (MariaDB
        # does not support the MySQL-8.0.20 ``AS new`` row-alias).
        return ins.on_duplicate_key_update({col: ins.inserted[col] for col in update})
    return ins.on_conflict_do_update(
        index_elements=list(conflict),
        set_={col: ins.excluded[col] for col in update},
    )


def insert_ignore(
    conn: Connection, table: Table, values: dict[str, Any], *, conflict: Sequence[str]
) -> int:
    """INSERT a row, doing nothing on a conflict over ``conflict`` columns.

    Returns 1 if a row was inserted, 0 if a conflicting row already existed. The count is read from
    ``RETURNING`` on Postgres/SQLite (``rowcount`` is unreliable for ``ON CONFLICT DO NOTHING`` on
    psycopg) and from ``rowcount`` on MySQL/MariaDB.

    Behaviour is identical across dialects: a *duplicate-key* conflict is skipped, but any other
    error (truncation, NOT-NULL, FK) still raises — unlike a bare ``INSERT IGNORE``.

    Args:
        conn: An open SQLAlchemy connection (inside a ``transaction()``).
        table: The target ``Table`` (from your metadata).
        values: Column → value mapping for the row.
        conflict: Columns of the unique/primary-key constraint to conflict on. On MySQL/MariaDB the
            conflict target is implicit (any duplicate key); on a table with multiple unique
            constraints, prefer the other dialects if you must scope to one specific constraint.
    """
    name = conn.dialect.name
    result = conn.execute(_insert_ignore_stmt(name, table, values, conflict))
    if name in _MYSQL_DIALECTS:
        return 1 if result.rowcount else 0
    return 1 if result.first() is not None else 0


def upsert(
    conn: Connection,
    table: Table,
    values: dict[str, Any],
    *,
    conflict: Sequence[str],
    update: Sequence[str],
) -> None:
    """INSERT a row, overwriting ``update`` columns from the incoming row on a conflict over
    ``conflict`` columns — the portable replacement for ``INSERT OR REPLACE``.

    Args:
        conn: An open SQLAlchemy connection.
        table: The target ``Table``.
        values: Column → value mapping for the row.
        conflict: Columns of the unique/primary-key constraint to conflict on. On MySQL/MariaDB the
            conflict target is implicit (``ON DUPLICATE KEY UPDATE``).
        update: Columns to overwrite from the incoming row when the row already exists. Must be
            non-empty.

    Raises:
        InvalidInputError: if ``conflict`` or ``update`` is empty.
    """
    if not conflict:
        raise InvalidInputError("upsert requires at least one `conflict` column")
    if not update:
        raise InvalidInputError("upsert requires at least one `update` column")
    conn.execute(_upsert_stmt(conn.dialect.name, table, values, conflict, update))
